/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Nemanja
 */
public class FLogin extends javax.swing.JFrame {

    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
        setLocationRelativeTo(null);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabUsername = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabPassword = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jBtnIzadji = new javax.swing.JButton();
        jBtnLogin = new javax.swing.JButton();
        jLabUsernameError = new javax.swing.JLabel();
        jLabPasswordError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Optimized-Za Kontica-page-001 (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prijavi se:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 56, -1, -1));

        jLabUsername.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabUsername.setText("Username:");
        jPanel1.add(jLabUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 135, -1, -1));

        jTxtUsername.setBackground(new java.awt.Color(51, 51, 51));
        jTxtUsername.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jTxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        jTxtUsername.setBorder(null);
        jTxtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 134, 190, 20));

        jLabPassword.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabPassword.setText("Password:");
        jPanel1.add(jLabPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 204, -1, -1));

        jTxtPassword.setBackground(new java.awt.Color(51, 51, 51));
        jTxtPassword.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPassword.setBorder(null);
        jPanel1.add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 201, 190, 20));

        jBtnIzadji.setBackground(new java.awt.Color(255, 255, 255));
        jBtnIzadji.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jBtnIzadji.setForeground(new java.awt.Color(51, 51, 51));
        jBtnIzadji.setText("IZADJI");
        jBtnIzadji.setBorder(null);
        jBtnIzadji.setBorderPainted(false);
        jBtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzadjiActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnIzadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 140, 50));

        jBtnLogin.setBackground(new java.awt.Color(223, 181, 107));
        jBtnLogin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jBtnLogin.setText("PRIJAVI SE");
        jBtnLogin.setBorderPainted(false);
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 140, 50));

        jLabUsernameError.setBackground(new java.awt.Color(51, 51, 51));
        jLabUsernameError.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabUsernameError.setForeground(new java.awt.Color(153, 0, 0));
        jLabUsernameError.setText(" ");
        jPanel1.add(jLabUsernameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 190, -1));

        jLabPasswordError.setBackground(new java.awt.Color(51, 51, 51));
        jLabPasswordError.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabPasswordError.setForeground(new java.awt.Color(153, 0, 0));
        jLabPasswordError.setText(" ");
        jPanel1.add(jLabPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 196, 14));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 196, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzadjiActionPerformed
        
    }//GEN-LAST:event_jBtnIzadjiActionPerformed

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        
    }//GEN-LAST:event_jBtnLoginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIzadji;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabPassword;
    private javax.swing.JLabel jLabPasswordError;
    private javax.swing.JLabel jLabUsername;
    private javax.swing.JLabel jLabUsernameError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables

    public void addButtonLoginListener(ActionListener ae){
        jBtnLogin.addActionListener(ae);
    }
    
    public void addButtonCancelListener(ActionListener ae){
        jBtnIzadji.addActionListener(ae);
    }
    
}
